spring.application.name=Sequence-Generator
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.url=jdbc:postgresql://localhost:5432/sequence_generator
spring.jpa.hibernate.ddl-auto=update

